[package]
name = "uiautomation"
version = "0.0.1"
edition = "2021"
authors = ["Steven Lee <leexgone@163.com>"]

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]

clap = "3.0"
chrono = "0.4"

[dependencies.windows]
version = "0.33"
features = [
    "Win32_Foundation",
    "Win32_System_Com",
    "Win32_System_Ole",
    "Win32_UI_Accessibility",
    "UI_UIAutomation"
]