[package]
name = "uiautomation"
version = "0.2.1"
edition = "2021"
license = "Apache-2.0"
authors = ["Steven Lee <leexgone@163.com>"]
description = "UI Automation Framework for Windows"
repository = "https://github.com/leexgone/uiautomation-rs"
homepage = "https://github.com/leexgone"
readme = "../../README.md"
keywords = ["windows", "uiautomation", "rpa"]
categories = ["api-bindings", "os::windows-apis", "accessibility"]

[package.metadata.docs.rs]
default-target = "x86_64-pc-windows-msvc"
targets = ["aarch64-pc-windows-msvc", "i686-pc-windows-msvc", "x86_64-pc-windows-msvc"]

[dependencies]

chrono = "0.4.22"
phf = { version = "0.11.1", features = ["macros"] }
uiautomation_derive = { version = "0.0.9", path = "../uiautomation_derive" }
# uiautomation_derive = "0.0.5"

[dependencies.windows]
version = "0.43.0"
features = [
    # "alloc",
    "Win32_Foundation",
    "Win32_System_Com",
    "Win32_System_Ole",
    "Win32_UI_Accessibility",
    "Win32_UI_Input_KeyboardAndMouse",
    "Win32_UI_WindowsAndMessaging",
    "Win32_System_Threading",
    "Win32_Security",
    "UI_UIAutomation"
]